
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.6 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/project/bioinformatics/WZhang_lab/s440820/Module_3_Yi/project/hop_example.py", line 2, in <module>
    from hop.data_loader import load_genehop
  File "/project/bioinformatics/WZhang_lab/s440820/Module_3_Yi/project/hop/data_loader.py", line 2, in <module>
    import pandas as pd
  File "/home2/s440820/.local/lib/python3.11/site-packages/pandas/__init__.py", line 49, in <module>
    from pandas.core.api import (
  File "/home2/s440820/.local/lib/python3.11/site-packages/pandas/core/api.py", line 28, in <module>
    from pandas.core.arrays import Categorical
  File "/home2/s440820/.local/lib/python3.11/site-packages/pandas/core/arrays/__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "/home2/s440820/.local/lib/python3.11/site-packages/pandas/core/arrays/arrow/__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "/home2/s440820/.local/lib/python3.11/site-packages/pandas/core/arrays/arrow/array.py", line 50, in <module>
    from pandas.core import (
  File "/home2/s440820/.local/lib/python3.11/site-packages/pandas/core/ops/__init__.py", line 8, in <module>
    from pandas.core.ops.array_ops import (
  File "/home2/s440820/.local/lib/python3.11/site-packages/pandas/core/ops/array_ops.py", line 56, in <module>
    from pandas.core.computation import expressions
  File "/home2/s440820/.local/lib/python3.11/site-packages/pandas/core/computation/expressions.py", line 21, in <module>
    from pandas.core.computation.check import NUMEXPR_INSTALLED
  File "/home2/s440820/.local/lib/python3.11/site-packages/pandas/core/computation/check.py", line 5, in <module>
    ne = import_optional_dependency("numexpr", errors="warn")
  File "/home2/s440820/.local/lib/python3.11/site-packages/pandas/compat/_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
  File "/cm/shared/apps/python/3.11.x-anaconda/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/cm/shared/apps/python/3.11.x-anaconda/lib/python3.11/site-packages/numexpr/__init__.py", line 24, in <module>
    from numexpr.interpreter import MAX_THREADS, use_vml, __BLOCK_SIZE1__
AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.6 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/project/bioinformatics/WZhang_lab/s440820/Module_3_Yi/project/hop_example.py", line 2, in <module>
    from hop.data_loader import load_genehop
  File "/project/bioinformatics/WZhang_lab/s440820/Module_3_Yi/project/hop/data_loader.py", line 2, in <module>
    import pandas as pd
  File "/home2/s440820/.local/lib/python3.11/site-packages/pandas/__init__.py", line 49, in <module>
    from pandas.core.api import (
  File "/home2/s440820/.local/lib/python3.11/site-packages/pandas/core/api.py", line 28, in <module>
    from pandas.core.arrays import Categorical
  File "/home2/s440820/.local/lib/python3.11/site-packages/pandas/core/arrays/__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "/home2/s440820/.local/lib/python3.11/site-packages/pandas/core/arrays/arrow/__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "/home2/s440820/.local/lib/python3.11/site-packages/pandas/core/arrays/arrow/array.py", line 64, in <module>
    from pandas.core.arrays.masked import BaseMaskedArray
  File "/home2/s440820/.local/lib/python3.11/site-packages/pandas/core/arrays/masked.py", line 60, in <module>
    from pandas.core import (
  File "/home2/s440820/.local/lib/python3.11/site-packages/pandas/core/nanops.py", line 52, in <module>
    bn = import_optional_dependency("bottleneck", errors="warn")
  File "/home2/s440820/.local/lib/python3.11/site-packages/pandas/compat/_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
  File "/cm/shared/apps/python/3.11.x-anaconda/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/cm/shared/apps/python/3.11.x-anaconda/lib/python3.11/site-packages/bottleneck/__init__.py", line 7, in <module>
    from .move import (move_argmax, move_argmin, move_max, move_mean, move_median,
AttributeError: _ARRAY_API not found
GeneHop:   0%|          | 0/150 [00:00<?, ?it/s]GeneHop:   1%|          | 1/150 [00:48<2:00:19, 48.46s/it]GeneHop:   1%|▏         | 2/150 [01:32<1:52:57, 45.80s/it]GeneHop:   2%|▏         | 3/150 [02:18<1:52:15, 45.82s/it]GeneHop:   3%|▎         | 4/150 [03:05<1:52:57, 46.42s/it]GeneHop:   3%|▎         | 5/150 [03:53<1:53:16, 46.87s/it]GeneHop:   4%|▍         | 6/150 [04:37<1:50:11, 45.91s/it]GeneHop:   5%|▍         | 7/150 [05:19<1:46:48, 44.81s/it]GeneHop:   5%|▌         | 8/150 [06:10<1:50:45, 46.80s/it]GeneHop:   6%|▌         | 9/150 [06:54<1:47:47, 45.87s/it]GeneHop:   7%|▋         | 10/150 [07:38<1:45:36, 45.26s/it]GeneHop:   7%|▋         | 11/150 [08:28<1:48:22, 46.78s/it]GeneHop:   8%|▊         | 12/150 [09:17<1:48:34, 47.21s/it]GeneHop:   9%|▊         | 13/150 [10:03<1:47:08, 46.92s/it]GeneHop:   9%|▉         | 14/150 [10:52<1:48:13, 47.74s/it]